### ISSUE TITLE
Apps Getting Started guide broken link

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/x-dash#119] opened 2018-07-26 10:00 UTC
The link to the 'Full Setup' guide under 'Slightly slower start' is broken in the generated docs: https://financial-times.github.io/x-dash/guides/apps/getting-started - I looked at the source Markdown file with the goal of opening a PR, but couldn't quite figure out what the path _should be_.

**Comment by i-like-robots** [comment] 2018-07-26 10:03
Duplicate of #67

**Closed by i-like-robots** 2018-07-26 10:03 UTC
Labels: bug, documentation, duplicate

**Comment by simonplend** [comment] 2018-07-26 13:44
Mah bad
