### ISSUE TITLE
Year 2018 is used

### ISSUE THREAD

**Issue by krumft** [Financial-Times/x-dash#539] opened 2020-10-11 20:18 UTC
https://github.com/Financial-Times/x-dash/blob/498902fd97b495b3e17e06a6651ac6ac3f0b733e/web/src/components/footer/index.jsx#L34

**Comment by apaleslimghost** [comment] 2020-10-12 08:02
duplicate of #533!

**Closed by apaleslimghost** 2020-10-12 08:02 UTC

**Comment by krumft** [comment] 2020-10-12 08:04
Oh, sorry, totally missed that
